import type { Locale } from '@/lib/i18n/config';

// Documentation publique de l'API v1 (marketplaces), par langue.
// Les exemples de code sont dans la page : ils ne dépendent pas de la langue.

const fr = {
  meta: {
    title: 'API Shede v1 — Documentation',
    description: 'Intégrez les restaurants Shede à votre marketplace de livraison : menu, commandes, livraison et webhooks.',
  },
  header: { docs: 'Documentation', api: 'API v1', back: 'Retour', onThisPage: 'Sur cette page', copy: 'Copier', copied: 'Copié !' },
  nav: {
    intro: 'Introduction',
    auth: 'Authentification',
    responses: 'Réponses et erreurs',
    limits: 'Limites',
    test: 'Mode test',
    point: 'GET /point',
    menu: 'GET /menu',
    categories: 'GET /categories',
    deliveryZones: 'GET /delivery-zones',
    lifecycle: 'Cycle d’une commande',
    createOrder: 'POST /orders',
    getOrder: 'GET /orders/{id}',
    listOrders: 'GET /orders',
    cancel: 'POST …/cancel',
    delivery: 'POST …/delivery-events',
    webhooks: 'Webhooks',
    signature: 'Vérifier la signature',
  },
  groups: { start: 'Démarrage', resources: 'Point, menu et livraison', orders: 'Commandes', webhooks: 'Webhooks' },
  intro: {
    badge: 'API v1',
    title: 'Intégrer Shede à votre marketplace',
    text: 'L’API Shede permet à une marketplace de livraison de récupérer le menu d’un restaurant, de lui transmettre des commandes et de suivre leur préparation en temps réel. Toutes les requêtes et réponses sont en JSON, sur HTTPS.',
    baseUrl: 'Adresse de base',
    flow: [
      'Le restaurant vous transmet sa clé d’API.',
      'Vous synchronisez son menu avec GET /menu.',
      'Vous envoyez chaque commande avec POST /orders.',
      'Le restaurant l’accepte ou la refuse dans Shede ; vous êtes prévenu par webhook.',
      'Votre livreur la récupère : vous l’indiquez avec POST /orders/{id}/delivery-events.',
    ],
  },
  auth: {
    title: 'Authentification',
    text: 'Chaque point de vente possède sa propre clé (shd_live_…), générée par l’administrateur de l’organisation dans Shede (Points & licence → fiche du point → API). La clé identifie le point : aucun autre identifiant n’est nécessaire. Une clé de test (shd_test_…) permet d’essayer l’API sans rien enregistrer (voir Mode test).',
    header: 'Envoyez-la dans l’en-tête Authorization (l’en-tête X-Api-Key est aussi accepté) :',
    warning: 'Gardez la clé côté serveur : ne l’intégrez jamais dans une application mobile ou une page web. Une clé régénérée ou révoquée cesse immédiatement de fonctionner.',
  },
  responses: {
    title: 'Réponses et erreurs',
    success: 'Succès : le résultat est dans data.',
    error: 'Erreur : un code stable et un message lisible (en français ou en anglais selon l’en-tête Accept-Language).',
    colHttp: 'HTTP',
    colCode: 'code',
    colMeaning: 'Signification',
    errors: [
      ['401', 'missing_key, invalid_key', 'Clé absente, inconnue ou révoquée'],
      ['403', 'module_disabled, license_inactive, point_inactive', 'Module API absent de la licence, licence expirée ou point désactivé'],
      ['403', 'quota_exceeded', 'Quota mensuel de commandes de l’organisation atteint'],
      ['404', 'not_found', 'Ressource introuvable'],
      ['409', 'point_paused', 'Le restaurant a mis les commandes marketplace en pause'],
      ['409', 'invalid_state', 'Action impossible dans l’état de la commande'],
      ['422', 'validation_error', 'Requête invalide : details précise les champs en cause'],
      ['429', 'rate_limited', 'Trop de requêtes (voir Retry-After)'],
      ['500', 'internal_error', 'Erreur interne, réessayez plus tard'],
    ],
    amounts: 'Montants en francs CFA (XAF), entiers. price est le prix saisi par le restaurant ; price_with_tax le prix TTC payé par le client, selon le régime de TVA du point (tax.prices_include_tax).',
  },
  limits: {
    title: 'Limites',
    rate: '60 requêtes par minute et par point. Chaque réponse indique X-RateLimit-Limit et X-RateLimit-Remaining ; au-delà, réponse 429 avec l’en-tête Retry-After (en secondes).',
    quota: 'Le nombre de commandes reçues par l’API chaque mois dépend de la licence du restaurant. Une fois le quota atteint, POST /orders répond 403 quota_exceeded jusqu’au mois suivant.',
  },
  test: {
    title: 'Mode test',
    text: 'Pour développer et tester votre intégration sans toucher aux données du restaurant, utilisez une clé de test (shd_test_…), générée au même endroit que la clé de production. Mêmes adresses, mêmes réponses : seul le préfixe de la clé change.',
    rules: [
      'Rien n’est enregistré : aucune commande, facture, sortie de stock, écriture comptable ni consommation du quota. Le restaurant ne voit rien.',
      'GET /point et GET /menu renvoient les vraies données du point ; GET /point indique livemode: false.',
      'POST /orders applique exactement les mêmes contrôles (produits, disponibilité, accompagnements, pause) et calcule les mêmes montants (promotions, TVA), puis renvoie une commande simulée avec livemode: false.',
      'L’id d’une commande de test commence par test_ et contient la commande : conservez-le, c’est lui qu’il faut utiliser avec GET /orders/{id} (la recherche par external_id n’est pas disponible en test). Il reste valable 7 jours.',
      'GET /orders renvoie toujours une liste vide.',
      'Annulation et événements du livreur suivent les mêmes règles et renvoient le résultat simulé, sans le conserver : un GET suivant renvoie la commande telle que la fait évoluer le temps.',
    ],
    timelineTitle: 'Évolution automatique du statut',
    colDelay: 'Depuis la création',
    colStatus: 'status',
    timeline: [
      ['0 – 30 s', 'pending_acceptance'],
      ['30 – 60 s', 'accepted (prep_minutes: 15)'],
      ['60 – 120 s', 'preparing'],
      ['après 2 min', 'ready'],
    ],
    reject: 'Pour tester un refus, terminez external_id par -reject : la commande passe à rejected au bout de 30 secondes. Avec delivery_by: restaurant, la course est attribuée à 2 min, en route à 3 min (picked_up) et livrée à 5 min (delivered).',
    webhookTitle: 'Webhooks de test',
    webhook: 'Aucun webhook n’est émis automatiquement en mode test. Déclenchez-en un à la demande : il est envoyé tout de suite à l’adresse de webhook du point, signé avec le même secret, marqué livemode: false, et la réponse indique le résultat de l’envoi. type : order.status_changed (avec order_id, et status pour forcer le statut annoncé), menu.updated, point.paused, point.resumed ou ping.',
  },
  point: {
    title: 'Le point de vente',
    text: 'Informations du restaurant associé à la clé, dont son régime de TVA. accepting_orders indique s’il accepte des commandes en ce moment (false si le restaurant a mis les commandes marketplace en pause — paused — ou si le point est désactivé) : vérifiez-le au démarrage et chaque fois qu’un webhook point.paused / point.resumed a pu être manqué.',
  },
  menu: {
    title: 'Le menu',
    text: 'Produits du point avec leurs accompagnements. Les produits indisponibles sont renvoyés avec is_available: false : masquez-les plutôt que de les supprimer. Le menu peut changer à tout moment : relisez-le à réception du webhook menu.updated. Chaque produit peut appartenir à plusieurs catégories (categories) ; is_deliverable: false signale un produit que le restaurant ne livre pas : ne le proposez pas, POST /orders le refuse (product_not_deliverable).',
  },
  categories: {
    title: 'Les catégories',
    text: 'Catégories du menu, dans l’ordre choisi par le restaurant : chaque catégorie principale (parent_id: null) suivie de ses sous-catégories (parent_id = id de la catégorie). Un seul niveau de sous-catégories. position donne l’ordre parmi les catégories de même niveau. Un produit apparaît dans chacune de ses catégories ou sous-catégories ; pour afficher une catégorie principale, incluez aussi les produits de ses sous-catégories. Les catégories masquées par le restaurant (et les sous-catégories d’une catégorie masquée) ne sont pas renvoyées. Elles changent avec le webhook menu.updated.',
  },
  deliveryZones: {
    title: 'Zones de livraison du restaurant',
    text: 'Si le restaurant livre lui-même (GET /point → restaurant_delivery: true), voici les quartiers ou secteurs qu’il dessert et les frais de chacun. fee est le montant saisi par le restaurant, fee_with_tax celui payé par le client. Liste vide si le restaurant ne livre pas. Relisez-la à réception du webhook delivery_zones.updated.',
    modes: 'Deux façons de livrer une commande (champ delivery_by de POST /orders) :',
    modeList: [
      ['marketplace', 'Par défaut. Votre livreur récupère la commande au restaurant ; vous suivez la course avec POST /orders/{id}/delivery-events.'],
      ['restaurant', 'Un livreur du restaurant livre le client dans la zone choisie (delivery.zone_id). Les frais de la zone s’ajoutent au total. Le suivi se fait dans Shede : delivery.status passe de to_assign à assigned, in_transit puis delivered (ou failed). La vente est clôturée à la livraison.'],
    ],
  },
  lifecycle: {
    title: 'Cycle de vie d’une commande',
    rules: [
      'Le restaurant accepte ou refuse chaque commande dans Shede, et annonce un temps de préparation (prep_minutes, estimated_ready_at).',
      'Shede fait foi pour les prix : le total (TVA incluse) est calculé à partir des prix du restaurant et renvoyé dans amounts.',
      'Vous encaissez le client et reversez le montant au restaurant : la vente est clôturée dans Shede quand votre livreur récupère la commande (PICKED_UP).',
    ],
    statuses: 'Statuts',
    statusList: [
      ['pending_acceptance', 'En attente de la décision du restaurant'],
      ['accepted', 'Acceptée, préparation pas encore commencée'],
      ['preparing', 'En préparation'],
      ['ready', 'Prête à être récupérée'],
      ['picked_up', 'Récupérée par le livreur (vente clôturée)'],
      ['delivered', 'Livrée au client'],
      ['delivery_failed', 'Livraison par le restaurant échouée (delivery.note)'],
      ['rejected', 'Refusée par le restaurant (rejection_reason)'],
      ['cancelled', 'Annulée (cancel_reason)'],
    ],
  },
  createOrder: {
    title: 'Créer une commande',
    fields: 'Champs',
    colField: 'Champ',
    colRequired: 'Obligatoire',
    colDescription: 'Description',
    yes: 'oui',
    no: 'non',
    fieldList: [
      ['external_id', true, 'Numéro de la commande chez vous (unique par point)'],
      ['partner', false, 'Nom de votre marketplace (glovo, yango…)'],
      ['customer.name', false, 'Nom du client'],
      ['customer.phone', true, 'Téléphone du client'],
      ['items[].product_id', true, 'Id d’un produit de GET /menu'],
      ['items[].quantity', true, '1 à 99'],
      ['items[].notes', false, 'Instruction pour la cuisine'],
      ['items[].accompaniments[]', false, 'id d’un accompagnement du produit ; quantity ≤ max_quantity (1 par défaut)'],
      ['notes', false, 'Note sur la commande'],
      ['delivery_address', false, 'Adresse de livraison (information pour le restaurant)'],
      ['delivery_by', false, 'marketplace (par défaut) ou restaurant'],
      ['delivery.zone_id', false, 'Obligatoire si delivery_by = restaurant : id d’une zone de GET /delivery-zones'],
      ['delivery.landmark', false, 'Obligatoire si delivery_by = restaurant : point de repère (3 caractères min.)'],
      ['delivery.district / city', false, 'Quartier (par défaut le nom de la zone) et ville'],
      ['delivery.lat / lng', false, 'Position GPS du client'],
    ] as [string, boolean, string][],
    response: 'Réponse 201 : la commande créée, au statut pending_acceptance.',
    idempotency: 'Idempotence : renvoyer la même requête (même external_id) ne crée pas de doublon ; la commande existante est renvoyée avec le code 200. En cas de coupure réseau, renvoyez simplement la requête.',
    validation: 'Erreurs de validation (422) — details[].code :',
  },
  getOrder: { title: 'Consulter une commande', text: '{id} est l’id Shede ou votre external_id.' },
  listOrders: {
    title: 'Lister les commandes',
    text: 'Deux usages : se resynchroniser après une coupure (updated_since) et rapprocher vos reversements (période de création et statut). Les filtres se combinent.',
    colParam: 'Paramètre',
    colDescription: 'Description',
    params: [
      ['updated_since', 'Commandes modifiées après cette date-heure ISO, triées par date de modification. Rappelez avec le updated_at de la dernière commande reçue.'],
      ['created_from', 'Créées à partir de cette date : YYYY-MM-DD (journée à Douala, UTC+1) ou date-heure ISO.'],
      ['created_to', 'Créées jusqu’à cette date incluse (YYYY-MM-DD), ou avant cette date-heure ISO.'],
      ['status', 'Un ou plusieurs statuts séparés par des virgules, ex. picked_up,delivered.'],
      ['limit', '1 à 100 (50 par défaut).'],
      ['offset', 'Nombre de commandes à sauter (pagination).'],
    ],
    paging: 'Sans updated_since, les commandes sont triées par date de création. La réponse contient has_more : true s’il reste des commandes ; rappelez avec offset augmenté de limit.',
  },
  cancel: {
    title: 'Annuler une commande',
    text: 'Possible tant que la préparation n’a pas commencé (pending_acceptance ou accepted) ; sinon 409 invalid_state.',
  },
  delivery: {
    title: 'Suivi de la livraison',
    text: 'status : ASSIGNED → PICKED_UP → DELIVERED, ou FAILED avec reason. Uniquement pour une commande acceptée livrée par la marketplace (sinon 409 restaurant_delivery). PICKED_UP (ou DELIVERED) clôture la vente côté restaurant : facture, stock et comptabilité.',
  },
  webhooks: {
    title: 'Webhooks',
    text: 'Shede prévient votre serveur dès qu’il se passe quelque chose sur le point. L’adresse (HTTPS) et le secret de signature sont configurés par le restaurant dans Shede : demandez-lui de vous transmettre le secret.',
    request: 'Requête envoyée',
    events: 'Événements',
    colType: 'type',
    colWhen: 'Quand',
    colData: 'data',
    eventList: [
      ['order.status_changed', 'La commande change de statut (acceptée, refusée, en préparation, prête, récupérée, livrée, annulée)', 'previous_status, order complète'],
      ['menu.updated', 'Un produit ou un accompagnement est créé, modifié, désactivé ou supprimé', 'product_id ou accompaniment_id, change → relisez GET /menu'],
      ['delivery_zones.updated', 'Une zone de livraison est créée, modifiée, activée ou désactivée', '— → relisez GET /delivery-zones'],
      ['point.paused / point.resumed', 'Le restaurant suspend ou reprend les commandes', 'paused'],
      ['ping', 'Test envoyé depuis Shede', '—'],
    ],
    replyTitle: 'Répondre',
    reply: 'Répondez 2xx en moins de 8 secondes et traitez l’événement ensuite. Sinon, l’envoi est retenté après 1 min, 5 min, 30 min, 2 h, 12 h et 24 h, puis abandonné. Un même événement peut arriver plusieurs fois : ignorez un Shede-Delivery déjà traité. L’ordre d’arrivée n’est pas garanti : fiez-vous à order.updated_at.',
  },
  signature: {
    title: 'Vérifier la signature',
    text: 'v1 est le HMAC-SHA256 du texte « {t}.{corps brut} » avec votre secret. Refusez les requêtes dont la signature ne correspond pas ou dont t a plus de 5 minutes. Utilisez le corps brut reçu, avant tout JSON.parse.',
  },
  tryIt: {
    open: 'Essayer',
    title: 'Essayer l’API',
    send: 'Envoyer',
    close: 'Fermer',
    credentials: 'Clé d’API',
    tokenPlaceholder: 'shd_test_…',
    toggleToken: 'Afficher ou masquer la clé',
    keyMemory: 'La clé reste dans cette page : elle n’est pas enregistrée et n’est envoyée qu’à l’API.',
    testHint: 'Utilisez une clé de test (shd_test_…) : rien n’est enregistré.',
    liveWarning: 'Clé de production : cette requête modifie de vraies données (commande, stock, comptabilité). Utilisez une clé de test pour essayer.',
    pathParams: 'Paramètres de chemin',
    queryParams: 'Paramètres de requête',
    addParam: 'Ajouter un paramètre',
    name: 'nom',
    value: 'valeur',
    remove: 'Retirer',
    body: 'Corps (JSON)',
    resetBody: 'Réinitialiser',
    invalidJson: 'Le corps n’est pas un JSON valide.',
    missingToken: 'Saisissez une clé d’API.',
    missingParam: 'Renseignez le paramètre {name}.',
    response: 'Réponse',
    empty: 'Cliquez sur Envoyer pour obtenir une réponse.',
    networkError: 'Erreur réseau : {message}',
    copyCurl: 'Copier en cURL',
    copyResponse: 'Copier la réponse',
    menuHint: 'Astuce : appelez d’abord GET /menu, un produit disponible sera prérempli dans POST /orders.',
    orderHint: 'L’id de la dernière commande créée est prérempli.',
  },
  footer: { version: 'API v1 · {year}', support: 'Une question sur l’intégration ? Contactez le support Shede.' },
};

export type ApiDocsContent = typeof fr;

const en: ApiDocsContent = {
  meta: {
    title: 'Shede API v1 — Documentation',
    description: 'Connect Shede restaurants to your delivery marketplace: menu, orders, delivery and webhooks.',
  },
  header: { docs: 'Documentation', api: 'API v1', back: 'Back', onThisPage: 'On this page', copy: 'Copy', copied: 'Copied!' },
  nav: {
    intro: 'Introduction',
    auth: 'Authentication',
    responses: 'Responses and errors',
    limits: 'Limits',
    test: 'Test mode',
    point: 'GET /point',
    menu: 'GET /menu',
    categories: 'GET /categories',
    deliveryZones: 'GET /delivery-zones',
    lifecycle: 'Order lifecycle',
    createOrder: 'POST /orders',
    getOrder: 'GET /orders/{id}',
    listOrders: 'GET /orders',
    cancel: 'POST …/cancel',
    delivery: 'POST …/delivery-events',
    webhooks: 'Webhooks',
    signature: 'Verify the signature',
  },
  groups: { start: 'Getting started', resources: 'Outlet, menu and delivery', orders: 'Orders', webhooks: 'Webhooks' },
  intro: {
    badge: 'API v1',
    title: 'Connect Shede to your marketplace',
    text: 'The Shede API lets a delivery marketplace read a restaurant’s menu, send it orders and follow their preparation in real time. All requests and responses are JSON over HTTPS.',
    baseUrl: 'Base URL',
    flow: [
      'The restaurant sends you its API key.',
      'You sync its menu with GET /menu.',
      'You send each order with POST /orders.',
      'The restaurant accepts or declines it in Shede; you are notified by webhook.',
      'Your courier picks it up: report it with POST /orders/{id}/delivery-events.',
    ],
  },
  auth: {
    title: 'Authentication',
    text: 'Each outlet has its own key (shd_live_…), generated by the organization administrator in Shede (Outlets & license → outlet page → API). The key identifies the outlet: no other identifier is needed. A test key (shd_test_…) lets you try the API without saving anything (see Test mode).',
    header: 'Send it in the Authorization header (the X-Api-Key header is also accepted):',
    warning: 'Keep the key on your server: never embed it in a mobile app or a web page. A regenerated or revoked key stops working immediately.',
  },
  responses: {
    title: 'Responses and errors',
    success: 'Success: the result is in data.',
    error: 'Error: a stable code and a readable message (in French or English depending on the Accept-Language header).',
    colHttp: 'HTTP',
    colCode: 'code',
    colMeaning: 'Meaning',
    errors: [
      ['401', 'missing_key, invalid_key', 'Missing, unknown or revoked key'],
      ['403', 'module_disabled, license_inactive, point_inactive', 'API module not in the license, expired license or disabled outlet'],
      ['403', 'quota_exceeded', 'The organization’s monthly order quota has been reached'],
      ['404', 'not_found', 'Resource not found'],
      ['409', 'point_paused', 'The restaurant has paused marketplace orders'],
      ['409', 'invalid_state', 'Action not possible in the order’s current state'],
      ['422', 'validation_error', 'Invalid request: details lists the fields involved'],
      ['429', 'rate_limited', 'Too many requests (see Retry-After)'],
      ['500', 'internal_error', 'Internal error, try again later'],
    ],
    amounts: 'Amounts are in CFA francs (XAF), integers. price is the price entered by the restaurant; price_with_tax is the price paid by the customer including VAT, depending on the outlet’s VAT mode (tax.prices_include_tax).',
  },
  limits: {
    title: 'Limits',
    rate: '60 requests per minute per outlet. Each response includes X-RateLimit-Limit and X-RateLimit-Remaining; above that, a 429 response with a Retry-After header (in seconds).',
    quota: 'The number of orders received through the API each month depends on the restaurant’s license. Once the quota is reached, POST /orders returns 403 quota_exceeded until the next month.',
  },
  test: {
    title: 'Test mode',
    text: 'To build and test your integration without touching the restaurant’s data, use a test key (shd_test_…), generated in the same place as the production key. Same URLs, same responses: only the key prefix changes.',
    rules: [
      'Nothing is saved: no order, invoice, stock movement, accounting entry or quota usage. The restaurant sees nothing.',
      'GET /point and GET /menu return the outlet’s real data; GET /point shows livemode: false.',
      'POST /orders runs exactly the same checks (products, availability, accompaniments, pause) and computes the same amounts (promotions, VAT), then returns a simulated order with livemode: false.',
      'A test order id starts with test_ and contains the order itself: keep it and use it with GET /orders/{id} (lookup by external_id is not available in test mode). It stays valid for 7 days.',
      'GET /orders always returns an empty list.',
      'Cancellation and courier events follow the same rules and return the simulated result without keeping it: a later GET returns the order as time moves it along.',
    ],
    timelineTitle: 'Automatic status progression',
    colDelay: 'Since creation',
    colStatus: 'status',
    timeline: [
      ['0 – 30 s', 'pending_acceptance'],
      ['30 – 60 s', 'accepted (prep_minutes: 15)'],
      ['60 – 120 s', 'preparing'],
      ['after 2 min', 'ready'],
    ],
    reject: 'To test a rejection, end external_id with -reject: the order becomes rejected after 30 seconds. With delivery_by: restaurant, the trip is assigned at 2 min, on its way at 3 min (picked_up) and delivered at 5 min (delivered).',
    webhookTitle: 'Test webhooks',
    webhook: 'No webhook is sent automatically in test mode. Trigger one on demand: it is sent immediately to the outlet’s webhook URL, signed with the same secret, marked livemode: false, and the response tells you how the delivery went. type: order.status_changed (with order_id, and status to force the announced status), menu.updated, point.paused, point.resumed or ping.',
  },
  point: {
    title: 'The outlet',
    text: 'Details of the restaurant linked to the key, including its VAT mode. accepting_orders tells whether it takes orders right now (false when the restaurant has paused marketplace orders — paused — or the outlet is disabled): check it at startup and whenever a point.paused / point.resumed webhook may have been missed.',
  },
  menu: {
    title: 'The menu',
    text: 'The outlet’s products with their side dishes. Unavailable products are returned with is_available: false: hide them rather than deleting them. The menu can change at any time: read it again when you receive the menu.updated webhook. Each product can belong to several categories (categories); is_deliverable: false marks a product the restaurant does not deliver: do not offer it, POST /orders rejects it (product_not_deliverable).',
  },
  categories: {
    title: 'Categories',
    text: 'Menu categories, in the order chosen by the restaurant: each main category (parent_id: null) followed by its subcategories (parent_id = the category id). Only one level of subcategories. position gives the order among categories of the same level. A product appears in each of its categories or subcategories; when showing a main category, also include the products of its subcategories. Categories hidden by the restaurant (and the subcategories of a hidden category) are not returned. They change with the menu.updated webhook.',
  },
  deliveryZones: {
    title: 'Restaurant delivery zones',
    text: 'When the restaurant delivers itself (GET /point → restaurant_delivery: true), these are the neighbourhoods or areas it serves and the fee for each. fee is the amount set by the restaurant, fee_with_tax what the customer pays. Empty list when the restaurant does not deliver. Read it again when you receive the delivery_zones.updated webhook.',
    modes: 'Two ways to deliver an order (delivery_by field of POST /orders):',
    modeList: [
      ['marketplace', 'Default. Your courier picks up the order at the restaurant; you report the trip with POST /orders/{id}/delivery-events.'],
      ['restaurant', 'A restaurant courier delivers the customer in the chosen zone (delivery.zone_id). The zone fee is added to the total. Tracking happens in Shede: delivery.status goes from to_assign to assigned, in_transit then delivered (or failed). The sale is closed on delivery.'],
    ],
  },
  lifecycle: {
    title: 'Order lifecycle',
    rules: [
      'The restaurant accepts or declines each order in Shede and announces a preparation time (prep_minutes, estimated_ready_at).',
      'Shede is the source of truth for prices: the total (VAT included) is calculated from the restaurant’s prices and returned in amounts.',
      'You charge the customer and pay the restaurant back: the sale is closed in Shede when your courier picks up the order (PICKED_UP).',
    ],
    statuses: 'Statuses',
    statusList: [
      ['pending_acceptance', 'Waiting for the restaurant’s decision'],
      ['accepted', 'Accepted, preparation not started yet'],
      ['preparing', 'Being prepared'],
      ['ready', 'Ready for pickup'],
      ['picked_up', 'Picked up by the courier (sale closed)'],
      ['delivered', 'Delivered to the customer'],
      ['delivery_failed', 'Restaurant delivery failed (delivery.note)'],
      ['rejected', 'Declined by the restaurant (rejection_reason)'],
      ['cancelled', 'Cancelled (cancel_reason)'],
    ],
  },
  createOrder: {
    title: 'Create an order',
    fields: 'Fields',
    colField: 'Field',
    colRequired: 'Required',
    colDescription: 'Description',
    yes: 'yes',
    no: 'no',
    fieldList: [
      ['external_id', true, 'Your order number (unique per outlet)'],
      ['partner', false, 'Your marketplace name (glovo, yango…)'],
      ['customer.name', false, 'Customer name'],
      ['customer.phone', true, 'Customer phone number'],
      ['items[].product_id', true, 'Id of a product from GET /menu'],
      ['items[].quantity', true, '1 to 99'],
      ['items[].notes', false, 'Instruction for the kitchen'],
      ['items[].accompaniments[]', false, 'id of a side dish of the product; quantity ≤ max_quantity (1 by default)'],
      ['notes', false, 'Note about the order'],
      ['delivery_address', false, 'Delivery address (for the restaurant’s information)'],
      ['delivery_by', false, 'marketplace (default) or restaurant'],
      ['delivery.zone_id', false, 'Required when delivery_by = restaurant: id of a zone from GET /delivery-zones'],
      ['delivery.landmark', false, 'Required when delivery_by = restaurant: landmark (at least 3 characters)'],
      ['delivery.district / city', false, 'Neighbourhood (defaults to the zone name) and city'],
      ['delivery.lat / lng', false, 'Customer GPS position'],
    ],
    response: '201 response: the created order, with the pending_acceptance status.',
    idempotency: 'Idempotency: sending the same request again (same external_id) does not create a duplicate; the existing order is returned with a 200 code. After a network failure, simply send the request again.',
    validation: 'Validation errors (422) — details[].code:',
  },
  getOrder: { title: 'Get an order', text: '{id} is the Shede id or your external_id.' },
  listOrders: {
    title: 'List orders',
    text: 'Two uses: resynchronize after an outage (updated_since) and reconcile your payouts (creation period and status). Filters can be combined.',
    colParam: 'Parameter',
    colDescription: 'Description',
    params: [
      ['updated_since', 'Orders changed after this ISO date-time, sorted by modification date. Call again with the updated_at of the last order received.'],
      ['created_from', 'Created from this date: YYYY-MM-DD (day in Douala, UTC+1) or ISO date-time.'],
      ['created_to', 'Created up to this date included (YYYY-MM-DD), or before this ISO date-time.'],
      ['status', 'One or more comma-separated statuses, e.g. picked_up,delivered.'],
      ['limit', '1 to 100 (default 50).'],
      ['offset', 'Number of orders to skip (pagination).'],
    ],
    paging: 'Without updated_since, orders are sorted by creation date. The response includes has_more: true when more orders remain; call again with offset increased by limit.',
  },
  cancel: {
    title: 'Cancel an order',
    text: 'Possible until preparation starts (pending_acceptance or accepted); otherwise 409 invalid_state.',
  },
  delivery: {
    title: 'Delivery tracking',
    text: 'status: ASSIGNED → PICKED_UP → DELIVERED, or FAILED with a reason. Only for an accepted order delivered by the marketplace (otherwise 409 restaurant_delivery). PICKED_UP (or DELIVERED) closes the sale on the restaurant’s side: invoice, stock and accounting.',
  },
  webhooks: {
    title: 'Webhooks',
    text: 'Shede notifies your server as soon as something happens at the outlet. The address (HTTPS) and the signing secret are set up by the restaurant in Shede: ask them to send you the secret.',
    request: 'Request sent',
    events: 'Events',
    colType: 'type',
    colWhen: 'When',
    colData: 'data',
    eventList: [
      ['order.status_changed', 'The order changes status (accepted, declined, preparing, ready, picked up, delivered, cancelled)', 'previous_status, full order'],
      ['menu.updated', 'A product or side dish is created, changed, disabled or deleted', 'product_id or accompaniment_id, change → read GET /menu again'],
      ['delivery_zones.updated', 'A delivery zone is created, changed, enabled or disabled', '— → read GET /delivery-zones again'],
      ['point.paused / point.resumed', 'The restaurant pauses or resumes orders', 'paused'],
      ['ping', 'Test sent from Shede', '—'],
    ],
    replyTitle: 'Replying',
    reply: 'Reply with a 2xx within 8 seconds and process the event afterwards. Otherwise the delivery is retried after 1 min, 5 min, 30 min, 2 h, 12 h and 24 h, then dropped. The same event can arrive several times: ignore a Shede-Delivery you have already processed. Delivery order is not guaranteed: rely on order.updated_at.',
  },
  signature: {
    title: 'Verify the signature',
    text: 'v1 is the HMAC-SHA256 of the text “{t}.{raw body}” with your secret. Reject requests whose signature does not match or whose t is more than 5 minutes old. Use the raw body as received, before any JSON.parse.',
  },
  tryIt: {
    open: 'Try it',
    title: 'Try the API',
    send: 'Send',
    close: 'Close',
    credentials: 'API key',
    tokenPlaceholder: 'shd_test_…',
    toggleToken: 'Show or hide the key',
    keyMemory: 'The key stays in this page: it is not stored and is only sent to the API.',
    testHint: 'Use a test key (shd_test_…): nothing is saved.',
    liveWarning: 'Production key: this request changes real data (order, stock, accounting). Use a test key to experiment.',
    pathParams: 'Path parameters',
    queryParams: 'Query parameters',
    addParam: 'Add parameter',
    name: 'name',
    value: 'value',
    remove: 'Remove',
    body: 'Body (JSON)',
    resetBody: 'Reset',
    invalidJson: 'The body is not valid JSON.',
    missingToken: 'Enter an API key.',
    missingParam: 'Fill in the {name} parameter.',
    response: 'Response',
    empty: 'Click Send to get a response.',
    networkError: 'Network error: {message}',
    copyCurl: 'Copy as cURL',
    copyResponse: 'Copy response',
    menuHint: 'Tip: call GET /menu first, an available product will be prefilled in POST /orders.',
    orderHint: 'The id of the last created order is prefilled.',
  },
  footer: { version: 'API v1 · {year}', support: 'A question about the integration? Contact Shede support.' },
};

export const API_DOCS_CONTENT: Record<Locale, ApiDocsContent> = { fr, en };
