import type { Locale } from '@/lib/i18n/config';

// Documentation publique de l'API v1 (marketplaces), par langue.
// Les exemples de code sont dans la page : ils ne dépendent pas de la langue.

const fr = {
  meta: {
    title: 'API Shede v1 — Documentation',
    description: 'Intégrez les restaurants Shede à votre marketplace de livraison : menu, commandes, livraison et webhooks.',
  },
  header: { docs: 'Documentation', api: 'API v1', back: 'Retour', onThisPage: 'Sur cette page', copy: 'Copier', copied: 'Copié !' },
  nav: {
    intro: 'Introduction',
    auth: 'Authentification',
    responses: 'Réponses et erreurs',
    limits: 'Limites',
    point: 'GET /point',
    menu: 'GET /menu',
    lifecycle: 'Cycle d’une commande',
    createOrder: 'POST /orders',
    getOrder: 'GET /orders/{id}',
    listOrders: 'GET /orders',
    cancel: 'POST …/cancel',
    delivery: 'POST …/delivery-events',
    webhooks: 'Webhooks',
    signature: 'Vérifier la signature',
  },
  groups: { start: 'Démarrage', resources: 'Point et menu', orders: 'Commandes', webhooks: 'Webhooks' },
  intro: {
    badge: 'API v1',
    title: 'Intégrer Shede à votre marketplace',
    text: 'L’API Shede permet à une marketplace de livraison de récupérer le menu d’un restaurant, de lui transmettre des commandes et de suivre leur préparation en temps réel. Toutes les requêtes et réponses sont en JSON, sur HTTPS.',
    baseUrl: 'Adresse de base',
    flow: [
      'Le restaurant vous transmet sa clé d’API.',
      'Vous synchronisez son menu avec GET /menu.',
      'Vous envoyez chaque commande avec POST /orders.',
      'Le restaurant l’accepte ou la refuse dans Shede ; vous êtes prévenu par webhook.',
      'Votre livreur la récupère : vous l’indiquez avec POST /orders/{id}/delivery-events.',
    ],
  },
  auth: {
    title: 'Authentification',
    text: 'Chaque point de vente possède sa propre clé (shd_live_…), générée par l’administrateur de l’organisation dans Shede (Points & licence → fiche du point → API). La clé identifie le point : aucun autre identifiant n’est nécessaire.',
    header: 'Envoyez-la dans l’en-tête Authorization (l’en-tête X-Api-Key est aussi accepté) :',
    warning: 'Gardez la clé côté serveur : ne l’intégrez jamais dans une application mobile ou une page web. Une clé régénérée ou révoquée cesse immédiatement de fonctionner.',
  },
  responses: {
    title: 'Réponses et erreurs',
    success: 'Succès : le résultat est dans data.',
    error: 'Erreur : un code stable et un message lisible (en français ou en anglais selon l’en-tête Accept-Language).',
    colHttp: 'HTTP',
    colCode: 'code',
    colMeaning: 'Signification',
    errors: [
      ['401', 'missing_key, invalid_key', 'Clé absente, inconnue ou révoquée'],
      ['403', 'module_disabled, license_inactive, point_inactive', 'Module API absent de la licence, licence expirée ou point désactivé'],
      ['403', 'quota_exceeded', 'Quota mensuel de commandes de l’organisation atteint'],
      ['404', 'not_found', 'Ressource introuvable'],
      ['409', 'point_paused', 'Le restaurant a mis les commandes marketplace en pause'],
      ['409', 'invalid_state', 'Action impossible dans l’état de la commande'],
      ['422', 'validation_error', 'Requête invalide : details précise les champs en cause'],
      ['429', 'rate_limited', 'Trop de requêtes (voir Retry-After)'],
      ['500', 'internal_error', 'Erreur interne, réessayez plus tard'],
    ],
    amounts: 'Montants en francs CFA (XAF), entiers. price est le prix saisi par le restaurant ; price_with_tax le prix TTC payé par le client, selon le régime de TVA du point (tax.prices_include_tax).',
  },
  limits: {
    title: 'Limites',
    rate: '60 requêtes par minute et par point. Chaque réponse indique X-RateLimit-Limit et X-RateLimit-Remaining ; au-delà, réponse 429 avec l’en-tête Retry-After (en secondes).',
    quota: 'Le nombre de commandes reçues par l’API chaque mois dépend de la licence du restaurant. Une fois le quota atteint, POST /orders répond 403 quota_exceeded jusqu’au mois suivant.',
  },
  point: { title: 'Le point de vente', text: 'Informations du restaurant associé à la clé, dont son régime de TVA.' },
  menu: {
    title: 'Le menu',
    text: 'Produits du point avec leurs accompagnements. Les produits indisponibles sont renvoyés avec is_available: false : masquez-les plutôt que de les supprimer. Le menu peut changer à tout moment : relisez-le à réception du webhook menu.updated.',
  },
  lifecycle: {
    title: 'Cycle de vie d’une commande',
    rules: [
      'Le restaurant accepte ou refuse chaque commande dans Shede, et annonce un temps de préparation (prep_minutes, estimated_ready_at).',
      'Shede fait foi pour les prix : le total (TVA incluse) est calculé à partir des prix du restaurant et renvoyé dans amounts.',
      'Vous encaissez le client et reversez le montant au restaurant : la vente est clôturée dans Shede quand votre livreur récupère la commande (PICKED_UP).',
    ],
    statuses: 'Statuts',
    statusList: [
      ['pending_acceptance', 'En attente de la décision du restaurant'],
      ['accepted', 'Acceptée, préparation pas encore commencée'],
      ['preparing', 'En préparation'],
      ['ready', 'Prête à être récupérée'],
      ['picked_up', 'Récupérée par le livreur (vente clôturée)'],
      ['delivered', 'Livrée au client'],
      ['rejected', 'Refusée par le restaurant (rejection_reason)'],
      ['cancelled', 'Annulée (cancel_reason)'],
    ],
  },
  createOrder: {
    title: 'Créer une commande',
    fields: 'Champs',
    colField: 'Champ',
    colRequired: 'Obligatoire',
    colDescription: 'Description',
    yes: 'oui',
    no: 'non',
    fieldList: [
      ['external_id', true, 'Numéro de la commande chez vous (unique par point)'],
      ['partner', false, 'Nom de votre marketplace (glovo, yango…)'],
      ['customer.name', false, 'Nom du client'],
      ['customer.phone', true, 'Téléphone du client'],
      ['items[].product_id', true, 'Id d’un produit de GET /menu'],
      ['items[].quantity', true, '1 à 99'],
      ['items[].notes', false, 'Instruction pour la cuisine'],
      ['items[].accompaniments[]', false, 'id d’un accompagnement du produit ; quantity ≤ max_quantity (1 par défaut)'],
      ['notes', false, 'Note sur la commande'],
      ['delivery_address', false, 'Adresse de livraison (information pour le restaurant)'],
    ] as [string, boolean, string][],
    response: 'Réponse 201 : la commande créée, au statut pending_acceptance.',
    idempotency: 'Idempotence : renvoyer la même requête (même external_id) ne crée pas de doublon ; la commande existante est renvoyée avec le code 200. En cas de coupure réseau, renvoyez simplement la requête.',
    validation: 'Erreurs de validation (422) — details[].code :',
  },
  getOrder: { title: 'Consulter une commande', text: '{id} est l’id Shede ou votre external_id.' },
  listOrders: {
    title: 'Se resynchroniser',
    text: 'Commandes modifiées depuis une date, de la plus ancienne à la plus récente (limit ≤ 100). Pour suivre les changements sans webhook, rappelez avec le updated_at de la dernière commande reçue.',
  },
  cancel: {
    title: 'Annuler une commande',
    text: 'Possible tant que la préparation n’a pas commencé (pending_acceptance ou accepted) ; sinon 409 invalid_state.',
  },
  delivery: {
    title: 'Suivi de la livraison',
    text: 'status : ASSIGNED → PICKED_UP → DELIVERED, ou FAILED avec reason. Uniquement pour une commande acceptée. PICKED_UP (ou DELIVERED) clôture la vente côté restaurant : facture, stock et comptabilité.',
  },
  webhooks: {
    title: 'Webhooks',
    text: 'Shede prévient votre serveur dès qu’il se passe quelque chose sur le point. L’adresse (HTTPS) et le secret de signature sont configurés par le restaurant dans Shede : demandez-lui de vous transmettre le secret.',
    request: 'Requête envoyée',
    events: 'Événements',
    colType: 'type',
    colWhen: 'Quand',
    colData: 'data',
    eventList: [
      ['order.status_changed', 'La commande change de statut (acceptée, refusée, en préparation, prête, récupérée, livrée, annulée)', 'previous_status, order complète'],
      ['menu.updated', 'Un produit ou un accompagnement est créé, modifié, désactivé ou supprimé', 'product_id ou accompaniment_id, change → relisez GET /menu'],
      ['point.paused / point.resumed', 'Le restaurant suspend ou reprend les commandes', 'paused'],
      ['ping', 'Test envoyé depuis Shede', '—'],
    ],
    replyTitle: 'Répondre',
    reply: 'Répondez 2xx en moins de 8 secondes et traitez l’événement ensuite. Sinon, l’envoi est retenté après 1 min, 5 min, 30 min, 2 h, 12 h et 24 h, puis abandonné. Un même événement peut arriver plusieurs fois : ignorez un Shede-Delivery déjà traité. L’ordre d’arrivée n’est pas garanti : fiez-vous à order.updated_at.',
  },
  signature: {
    title: 'Vérifier la signature',
    text: 'v1 est le HMAC-SHA256 du texte « {t}.{corps brut} » avec votre secret. Refusez les requêtes dont la signature ne correspond pas ou dont t a plus de 5 minutes. Utilisez le corps brut reçu, avant tout JSON.parse.',
  },
  footer: { version: 'API v1 · {year}', support: 'Une question sur l’intégration ? Contactez le support Shede.' },
};

export type ApiDocsContent = typeof fr;

const en: ApiDocsContent = {
  meta: {
    title: 'Shede API v1 — Documentation',
    description: 'Connect Shede restaurants to your delivery marketplace: menu, orders, delivery and webhooks.',
  },
  header: { docs: 'Documentation', api: 'API v1', back: 'Back', onThisPage: 'On this page', copy: 'Copy', copied: 'Copied!' },
  nav: {
    intro: 'Introduction',
    auth: 'Authentication',
    responses: 'Responses and errors',
    limits: 'Limits',
    point: 'GET /point',
    menu: 'GET /menu',
    lifecycle: 'Order lifecycle',
    createOrder: 'POST /orders',
    getOrder: 'GET /orders/{id}',
    listOrders: 'GET /orders',
    cancel: 'POST …/cancel',
    delivery: 'POST …/delivery-events',
    webhooks: 'Webhooks',
    signature: 'Verify the signature',
  },
  groups: { start: 'Getting started', resources: 'Outlet and menu', orders: 'Orders', webhooks: 'Webhooks' },
  intro: {
    badge: 'API v1',
    title: 'Connect Shede to your marketplace',
    text: 'The Shede API lets a delivery marketplace read a restaurant’s menu, send it orders and follow their preparation in real time. All requests and responses are JSON over HTTPS.',
    baseUrl: 'Base URL',
    flow: [
      'The restaurant sends you its API key.',
      'You sync its menu with GET /menu.',
      'You send each order with POST /orders.',
      'The restaurant accepts or declines it in Shede; you are notified by webhook.',
      'Your courier picks it up: report it with POST /orders/{id}/delivery-events.',
    ],
  },
  auth: {
    title: 'Authentication',
    text: 'Each outlet has its own key (shd_live_…), generated by the organization administrator in Shede (Outlets & license → outlet page → API). The key identifies the outlet: no other identifier is needed.',
    header: 'Send it in the Authorization header (the X-Api-Key header is also accepted):',
    warning: 'Keep the key on your server: never embed it in a mobile app or a web page. A regenerated or revoked key stops working immediately.',
  },
  responses: {
    title: 'Responses and errors',
    success: 'Success: the result is in data.',
    error: 'Error: a stable code and a readable message (in French or English depending on the Accept-Language header).',
    colHttp: 'HTTP',
    colCode: 'code',
    colMeaning: 'Meaning',
    errors: [
      ['401', 'missing_key, invalid_key', 'Missing, unknown or revoked key'],
      ['403', 'module_disabled, license_inactive, point_inactive', 'API module not in the license, expired license or disabled outlet'],
      ['403', 'quota_exceeded', 'The organization’s monthly order quota has been reached'],
      ['404', 'not_found', 'Resource not found'],
      ['409', 'point_paused', 'The restaurant has paused marketplace orders'],
      ['409', 'invalid_state', 'Action not possible in the order’s current state'],
      ['422', 'validation_error', 'Invalid request: details lists the fields involved'],
      ['429', 'rate_limited', 'Too many requests (see Retry-After)'],
      ['500', 'internal_error', 'Internal error, try again later'],
    ],
    amounts: 'Amounts are in CFA francs (XAF), integers. price is the price entered by the restaurant; price_with_tax is the price paid by the customer including VAT, depending on the outlet’s VAT mode (tax.prices_include_tax).',
  },
  limits: {
    title: 'Limits',
    rate: '60 requests per minute per outlet. Each response includes X-RateLimit-Limit and X-RateLimit-Remaining; above that, a 429 response with a Retry-After header (in seconds).',
    quota: 'The number of orders received through the API each month depends on the restaurant’s license. Once the quota is reached, POST /orders returns 403 quota_exceeded until the next month.',
  },
  point: { title: 'The outlet', text: 'Details of the restaurant linked to the key, including its VAT mode.' },
  menu: {
    title: 'The menu',
    text: 'The outlet’s products with their side dishes. Unavailable products are returned with is_available: false: hide them rather than deleting them. The menu can change at any time: read it again when you receive the menu.updated webhook.',
  },
  lifecycle: {
    title: 'Order lifecycle',
    rules: [
      'The restaurant accepts or declines each order in Shede and announces a preparation time (prep_minutes, estimated_ready_at).',
      'Shede is the source of truth for prices: the total (VAT included) is calculated from the restaurant’s prices and returned in amounts.',
      'You charge the customer and pay the restaurant back: the sale is closed in Shede when your courier picks up the order (PICKED_UP).',
    ],
    statuses: 'Statuses',
    statusList: [
      ['pending_acceptance', 'Waiting for the restaurant’s decision'],
      ['accepted', 'Accepted, preparation not started yet'],
      ['preparing', 'Being prepared'],
      ['ready', 'Ready for pickup'],
      ['picked_up', 'Picked up by the courier (sale closed)'],
      ['delivered', 'Delivered to the customer'],
      ['rejected', 'Declined by the restaurant (rejection_reason)'],
      ['cancelled', 'Cancelled (cancel_reason)'],
    ],
  },
  createOrder: {
    title: 'Create an order',
    fields: 'Fields',
    colField: 'Field',
    colRequired: 'Required',
    colDescription: 'Description',
    yes: 'yes',
    no: 'no',
    fieldList: [
      ['external_id', true, 'Your order number (unique per outlet)'],
      ['partner', false, 'Your marketplace name (glovo, yango…)'],
      ['customer.name', false, 'Customer name'],
      ['customer.phone', true, 'Customer phone number'],
      ['items[].product_id', true, 'Id of a product from GET /menu'],
      ['items[].quantity', true, '1 to 99'],
      ['items[].notes', false, 'Instruction for the kitchen'],
      ['items[].accompaniments[]', false, 'id of a side dish of the product; quantity ≤ max_quantity (1 by default)'],
      ['notes', false, 'Note about the order'],
      ['delivery_address', false, 'Delivery address (for the restaurant’s information)'],
    ],
    response: '201 response: the created order, with the pending_acceptance status.',
    idempotency: 'Idempotency: sending the same request again (same external_id) does not create a duplicate; the existing order is returned with a 200 code. After a network failure, simply send the request again.',
    validation: 'Validation errors (422) — details[].code:',
  },
  getOrder: { title: 'Get an order', text: '{id} is the Shede id or your external_id.' },
  listOrders: {
    title: 'Resynchronize',
    text: 'Orders changed since a date, oldest first (limit ≤ 100). To follow changes without webhooks, call again with the updated_at of the last order received.',
  },
  cancel: {
    title: 'Cancel an order',
    text: 'Possible until preparation starts (pending_acceptance or accepted); otherwise 409 invalid_state.',
  },
  delivery: {
    title: 'Delivery tracking',
    text: 'status: ASSIGNED → PICKED_UP → DELIVERED, or FAILED with a reason. Only for an accepted order. PICKED_UP (or DELIVERED) closes the sale on the restaurant’s side: invoice, stock and accounting.',
  },
  webhooks: {
    title: 'Webhooks',
    text: 'Shede notifies your server as soon as something happens at the outlet. The address (HTTPS) and the signing secret are set up by the restaurant in Shede: ask them to send you the secret.',
    request: 'Request sent',
    events: 'Events',
    colType: 'type',
    colWhen: 'When',
    colData: 'data',
    eventList: [
      ['order.status_changed', 'The order changes status (accepted, declined, preparing, ready, picked up, delivered, cancelled)', 'previous_status, full order'],
      ['menu.updated', 'A product or side dish is created, changed, disabled or deleted', 'product_id or accompaniment_id, change → read GET /menu again'],
      ['point.paused / point.resumed', 'The restaurant pauses or resumes orders', 'paused'],
      ['ping', 'Test sent from Shede', '—'],
    ],
    replyTitle: 'Replying',
    reply: 'Reply with a 2xx within 8 seconds and process the event afterwards. Otherwise the delivery is retried after 1 min, 5 min, 30 min, 2 h, 12 h and 24 h, then dropped. The same event can arrive several times: ignore a Shede-Delivery you have already processed. Delivery order is not guaranteed: rely on order.updated_at.',
  },
  signature: {
    title: 'Verify the signature',
    text: 'v1 is the HMAC-SHA256 of the text “{t}.{raw body}” with your secret. Reject requests whose signature does not match or whose t is more than 5 minutes old. Use the raw body as received, before any JSON.parse.',
  },
  footer: { version: 'API v1 · {year}', support: 'A question about the integration? Contact Shede support.' },
};

export const API_DOCS_CONTENT: Record<Locale, ApiDocsContent> = { fr, en };
